### ISSUE TITLE
Using Playlistloader in Party mode may cause scores to submit to scoresaber.

### ISSUE THREAD

**Issue by Flewrider** [rithik-b/PlaylistLoaderPlugin#11]
I played a few maps in Party mode and all of the scores submitted except for one which I did in NF and where I already had a better score on the map.
I think playlistloader breakes something in the game when using party mode.
If you need logs or something tell me where to look.

**Comment by rithik-b** [comment]
Hmm, I remember sending this info to scoresaber devs, didn't know PlaylistLoader was at fault back then.
Will be doing some testing and will keep you updated

**Comment by Flewrider** [comment]
I actually don't know if it's playlistloaders fault or scoresaber. I posted it in the scoresaber discord pc bug report section too but never got anything back on it. If you find out that its their fault don't stress about just closing this issue
