### ISSUE TITLE
Visual bug(?) when scrolling playlists

### ISSUE THREAD

**Issue by boulders2000** [rithik-b/PlaylistLoaderPlugin#16]
![unknown](https://user-images.githubusercontent.com/67582740/97751968-7b1ff880-1af3-11eb-8c55-9fc52676ef6f.png)
when scrolling through the playlists the images show to soon and hide to slow, making them cover the "all songs" button.
wont do anything with that button anyway while scrolling so its more of a visual thingy

screenshot included shows the noodlemas playlist hovering over the buttton while scrolling

**Comment by rithik-b** [comment]
Since this is using the scrolling that is part of the base game, I can’t do much about it without making the plugin too bloated and hard to maintain
