### ISSUE TITLE
Does not return to playlist when level is finished

### ISSUE THREAD

**Issue by nissel** [rithik-b/PlaylistLoaderPlugin#2]
Plugin is mostly working great, having a small issue, not sure if this it's with the plugin or just how playlists work.

When the level is over you are dropped back to the menu in custom song selection, at the top of the list. It would be much nicer if it could go back to the current playlist with the previous song selected. This happens in solo and party mode.

If you quit to menu from the pause screen you return to the playlist correctly, can this happen at the end of a song too?

**Comment by rithik-b** [comment]
Hi,
Unfortunately that's how the playlists view works in the main game
