### ISSUE TITLE
Song display arrangement problem

### ISSUE THREAD

**Issue by loyle5** [rithik-b/PlaylistLoaderPlugin#9]
When there are more songs in a playlist, they will not be displayed in the already arranged order
And you can see that the correct order is displayed in both beatlist and BeatDrop

At present, what I have tested is that when there are at most 16 songs in a playlist, everything is display right, but when it reaches 17 songs, it will be arranged in a-z way.

I don't know if this problem is due to the limitation of main game

**Comment by rithik-b** [comment]
It's a limitation with the base game unfortunately
